### ISSUE TITLE
最后两个综合练习能不能多提供一些数据

### ISSUE THREAD

**Issue by qinsJs** [hencoder/PracticeDraw1#10]
举个栗子，饼状图 能不能提供一下具体的比率值  
Lollipop 占比多少  
KitKat 占比多少  
Marshmallow 占比多少  

话说 最后两个练习的难道是  锵锵 的上升

**Comment by rengwuxian** [comment]
不用做得一样，大致差不多就行了，关键是掌握，不必追求完全一致。

**Comment by qinsJs** [comment]
可是朱老师我有强迫症怎么办 0 - 0

**Comment by rengwuxian** [comment]
后面的练习项目就都有源码示例了哈哈

**Comment by qinsJs** [comment]
这些数据是我在网上百度
![安卓系统分布图](http://p0.ifengimg.com/haina/2016_24/0584a3f053bdb59_w600_h417.png)

因为上面是一张图片，不方便复制，所以我简单整理一下

|Version|占比|颜色|
|---|---|----|
|Froyo| 0.1% | 忽略掉他吧|
|GingerBread| 2% | ac00b1|
|Ice Cream Sandwich| 1.9% | 9e9e9e|
|Jelly Bean| 6.8+9.4+2.7 = 18.9% | 009c8a|
|KitKat |31.6%  |  0090f7|
|Lollopop |35.4%  |ff0013|
|Marshmallow| 10.1%  |ffc200|


这个数据和朱老师的数据有细微的差距，使用的时候酌情。  
希望可以帮助其他童鞋。

**Comment by qinsJs** [comment]
### sample
最后简单的分享一下自己的作业，代码虽渣，也许可以帮助其他童鞋

因为最后两个练习对数据都进行了使用，所以我做了一个简陋的封装
```java
public class 我是提供数据的
{

	public static List<Bean> getData()
	{
		List<Bean> result = new ArrayList<>();
		result.add(new Bean("Froyo", 0.1f, Color.BLUE));
		result.add(new Bean("GingerBread", 2f, 0xffac00b1));
		result.add(new Bean("Ice Cream Sandwich", 1.9f, 0xff9e9e9e));
		result.add(new Bean("Jelly Bean", 18.9f, 0xff009c8a));
		result.add(new Bean("KitKat", 31.6f, 0xff0090f7));
		result.add(new Bean("Lollopop", 35.4f, 0xffff0013));
		result.add(new Bean("Marshmallow", 10.1f, 0xffffc200));

		return result;
	}

	public static class Bean
	{
		public String versionName;
		public float 比例;
		public int color;

		public Bean(String versionName, float 比例, int color)
		{
			this.versionName = versionName;
			this.比例 = 比例/100;
			this.color = color;
		}
	}
}
```

这是我完成的 [直方图](https://github.com/WardenAndroid/PracticeDraw1/blob/master/app/src/main/java/com/hencoder/hencoderpracticedraw1/practice/Practice10HistogramView.java) 作业,效果  
![](https://github.com/WardenAndroid/PracticeDraw1/blob/master/images/zhif.png?raw=true)

这是我完成的 [饼状图](https://github.com/WardenAndroid/PracticeDraw1/blob/master/app/src/main/java/com/hencoder/hencoderpracticedraw1/practice/Practice11PieChartView.java) 作业，效果  
![](https://github.com/WardenAndroid/PracticeDraw1/blob/master/images/bing.png?raw=true)


至于为什么只有图形而没有文字，O__O "…  
因为我还没有学到哪里去，才不是因为我懒 (,,• ₃ •,,)
