### ISSUE TITLE
可以有个样式的自定义view例子么

### ISSUE THREAD

**Issue by fangithubgithub** [hencoder/PracticeDraw1#4]
https://user-images.githubusercontent.com/20292386/28048372-20d08cec-6623-11e7-93ea-5058340cdd61.png[
![o xr 1a3becim _w 57 r3k](https://user-images.githubusercontent.com/20292386/28048453-9d7055de-6623-11e7-89dc-356a33f698cb.png)
](url)

**Comment by LitterSun** [comment]
仔细看完博主的博客和例子，我觉得实现这个应该不难吧

**Comment by fangithubgithub** [comment]
@LitterSun 来一个写一下

**Comment by LitterSun** [comment]
@fangithubgithub 继承LinearLayout或者RelativeLayout，放三个Button，然后绘制一个Path。很难？

**Comment by fangithubgithub** [comment]
@LitterSun 嗯，很难

**Comment by fangithubgithub** [comment]
不知道什么叫会了不难难了不会么

**Comment by fangithubgithub** [comment]
@LitterSun  不知道什么叫会了不难难了不会么

**Comment by fangithubgithub** [comment]
可不可以代码写出来 @LitterSun

**Comment by LitterSun** [comment]
@fangithubgithub 年轻人，不要拿来主义。自己不去实现，不走一点弯路，永远都成长不起来的。思路已经给你了，自己尝试一下吧。

**Comment by fangithubgithub** [comment]
@LitterSun 说了一堆废话，和XXXX...一样，呵呵

**Comment by JichunMa** [comment]
饼图 https://gist.github.com/JichunMa/a341be60974e822f55a3b7ab508efe65
条形图 https://gist.github.com/JichunMa/cdf755467f790df71199df0b171e3a5a
@LitterSun 
个人蠢作，仅供参考，如有问题，欢迎指出。

**Comment by aohanyao** [comment]
刚好，我项目中有类似的。 这个不需要自定义View，使用Clipchildren属性就能做到。

**Comment by fangithubgithub** [comment]
@aohanyao 有相关代码段可以贴出来么

**Comment by LitterSun** [comment]
@aohanyao 哈哈，Clipchildren确实可以，实在不行，把曲线路径也做成一张图，然后作为Layout的背景。

**Comment by fangithubgithub** [comment]
@LitterSun 你是真闲啊，属欠的，你是哪里人

**Comment by fangithubgithub** [comment]
世界之大唯剑不快 @LitterSun
